In [ ]:
import random

#임의의 숫자 100개 생성
a = [random.randint(0,1000) for i in range(100)]

#오름차순 정렬
numbers = sorted(a)

print(a)
print(numbers)

[847, 604, 516, 564, 690, 200, 982, 134, 312, 766, 175, 980, 484, 274, 984, 764, 601, 713, 666, 87, 488, 519, 519, 400, 548, 788, 959, 789, 828, 928, 200, 446, 931, 766, 829, 125, 94, 567, 687, 792, 71, 111, 159, 59, 886, 335, 605, 585, 991, 507, 70, 165, 826, 92, 219, 137, 167, 867, 697, 904, 360, 26, 828, 95, 615, 574, 206, 763, 566, 485, 553, 455, 412, 78, 332, 978, 656, 768, 88, 189, 212, 183, 122, 119, 351, 403, 712, 381, 825, 971, 521, 300, 50, 170, 622, 312, 553, 942, 722, 445]
[26, 50, 59, 70, 71, 78, 87, 88, 92, 94, 95, 111, 119, 122, 125, 134, 137, 159, 165, 167, 170, 175, 183, 189, 200, 200, 206, 212, 219, 274, 300, 312, 312, 332, 335, 351, 360, 381, 400, 403, 412, 445, 446, 455, 484, 485, 488, 507, 516, 519, 519, 521, 548, 553, 553, 564, 566, 567, 574, 585, 601, 604, 605, 615, 622, 656, 666, 687, 690, 697, 712, 713, 722, 763, 764, 766, 766, 768, 788, 789, 792, 825, 826, 828, 828, 829, 847, 867, 886, 904, 928, 931, 942, 959, 971, 978, 980, 982, 984, 991]


In [ ]:
import numpy as np

#임의의 두 4x4 matrix 생성
A = np.random.randint(0,100,(4,4))
B = np.random.randint(0,100,(4,4))

#두 matrix의 곱
C = np.dot(A,B)

#matirx C의 inverse 계산
C_det = np.linalg.det(C) #C의 determinant
C_trans = np.transpose(C) #C의 전치행렬
C_cofactor = np.zeros((4,4))

for row in range(4):
  for col in range(4):
    C_minor = np.delete(np.delete(C_trans, row, axis=0), col, axis=1) #소행렬 계산
    C_cofactor[row,col]=((-1) ** (row + col)) * np.linalg.det(C_minor) #여인자 계산

C_inv = C_cofactor/C_det

#Identity matrix 확인
I = np.dot(C,C_inv)

print(A)
print(B)
print(C)
print(C_inv)
print(I)

[[84 93 54 45]
 [72 44 70 97]
 [32 77 72 95]
 [31 39 30 57]]
[[99 32 49 81]
 [ 8 23 99 34]
 [70 60 18 69]
 [35 60 91 85]]
[[14415 10767 18390 17517]
 [15775 13336 17971 20403]
 [12149 12815 19132 18253]
 [ 7476  7109 11107 10752]]
[[ 0.00051766  0.00010125  0.00058597 -0.00203026]
 [ 0.00028341  0.00017686  0.00168546 -0.00365864]
 [ 0.00025072 -0.00027898  0.00021612 -0.00024599]
 [-0.00080632  0.00010085 -0.00174509  0.0041778 ]]
[[ 1.00000000e+00 -1.66971471e-14  8.34629674e-14 -1.49148055e-13]
 [ 1.90935592e-14  1.00000000e+00  9.80376804e-14 -1.52943630e-13]
 [ 1.41853760e-14 -1.55730463e-14  1.00000000e+00 -1.51701568e-13]
 [ 8.71525074e-15 -9.54791801e-15  5.51780843e-14  1.00000000e+00]]


In [ ]:
#Error bound
tol=10**(-8)

#주어진 함수
def f(x):

  return x**5 -9*x**4 - x**3 + 17*x**2 - 8*x - 8

#구간 설정
A = [-10, -1, 0]
B = [-1, 0, 10]

#bisection 함수 정의
def bisection(a, b):
  if f(a)*f(b)>0:
      print("부적절한 구간 설정")
  else:
    j = 0 #계산 횟수
    while b-a > tol:
      m = a + (b-a)/2
      if f(a)*f(m)<0:
        b = m
      else:
        a = m
      j += 1
    print("근사해:",m," 계산 횟수:",j)

for i in range(len(A)):
  bisection(A[i],B[i])

근사해: -1.3875071099027991  계산 횟수: 30
근사해: -0.5104293450713158  계산 횟수: 27
근사해: 8.910696404054761  계산 횟수: 30


In [ ]:
#Error bound
tol=10**(-8)

#주어진 함수
def f(x):

  return x**5 - 9*x**4 - x**3 + 17*x**2 - 8*x - 8

#도함수
def fp(x):

  return 5*x**4 - 36*x**3 - 3*x**2 + 34*x - 8

#초기값 설정
x_0 = [-10, -0.1, 10]

#newton 함수 정의
def newton(x):
  i = 0 #계산 횟수
  while True:
    x_n = x - f(x)/fp(x)
    if abs(x_n - x) < tol:
      break
    x = x_n
    i += 1
  print("근사해:",x_n, "계산 횟수", i)

for i in range(len(x_0)):
  newton(x_0[i])

근사해: -1.3875071055826167 계산 횟수 12
근사해: -0.5104293428178256 계산 횟수 4
근사해: 8.910696402960298 계산 횟수 5


In [ ]:
#Error bound
tol=10**(-8)

#주어진 함수
def f(x):

  return x**5 - 9*x**4 - x**3 + 17*x**2 - 8*x - 8

#도함수
def fp(x):

  return 5*x**4 - 36*x**3 - 3*x**2 + 34*x - 8

#초기값 설정
x_0 = [0]

#newton 함수 정의
def newton(x):
  i = 0 #계산 횟수
  while True:
    x_n = x - f(x)/fp(x)
    if abs(x_n - x) < tol:
      break
    x = x_n
    i += 1
  print("근사해:",x_n, "계산 횟수", i)

for i in range(len(x_0)):
  newton(x_0[i])

KeyboardInterrupt: 

In [ ]:
#Error bound
tol=10**(-8)

#주어진 함수
def f(x):

  return x**5 - 9*x**4 - x**3 + 17*x**2 - 8*x - 8

#secant 함수 정의
def secant(x_1, x_2):
  i = 0 #계산 횟수
  while True:
    x_3 = x_2 - f(x_2)*(x_2 - x_1)/(f(x_2) - f(x_1))
    if abs(x_3 - x_2) < tol:
      break
    x_1 = x_2
    x_2 = x_3
    i += 1
  print("근사해:",x_3, "계산 횟수", i)

secant(-10, -9.9)
secant(-0.1, -0.2)
secant(10, 9.9)

근사해: -1.387507105582635 계산 횟수 17
근사해: -0.5104293428178256 계산 횟수 5
근사해: 8.910696402960298 계산 횟수 6
